input_numbers = input("Enter numbers separated by spaces: ")
number_list = list(map(float, input_numbers.split()))
total = sum(number_list)
average = total / len(number_list)
print("List:", number_list)
print("Sum:", total)
print("Average:", average)
print("Max:", max(number_list))
print("Min:", min(number_list))